### ISSUE TITLE
The action doesn't upload all the files at once

### ISSUE THREAD

**Issue by OmarZeidan** [mattdelliott/cf-cli#1]
I am trying to have a wildcard upload to all my SVGs, but it only upload the first file? Any help?

Example:

```
cloudfiles-upload -u XXXXX -k YYYYY -c assets-images/svgs -f svgs/common/*.svg -r LON 
```

**Comment by mattdelliott** [comment]
Sorry I didn't get notifications for this repo. I know it's been a year and a half, but if you need help, let me know. Though I don't think it currently supports wildcards.
